### ISSUE TITLE
Error on python 2.7

### ISSUE THREAD

**Issue by Tsumiki-Chan** [elias94/pyomegle#1]
I get the following error:

``` python
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/pyomegle/pyomegle.py", line 32, in run
    self.instance.client_id = data['clientID']
KeyError: 'clientID'
```

Is this problem related to the api?

**Comment by openbrace** [comment]
Happens when your clientID is 1) revoked 2) proxy web servers 3) VPN services.
