### ISSUE TITLE
'RECAPTCHA_CHALLENGE_URL' is not defined when a CAPTCHA is detected

### ISSUE THREAD

**Issue by harrydayexe** [elias94/pyomegle#17]
I copied and pasted the setup code in the readme and started running, I knew I would face a captcha as I normally do however I received an error. Is this because the reCaptcha has changed slightly???
```
Traceback (most recent call last):
  File "/Users/harryday/.pyenv/versions/3.9.0/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/Users/harryday/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyomegle/pyomegle.py", line 33, in run
    self.instance._handle_events(data['events'])
  File "/Users/harryday/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyomegle/pyomegle.py", line 98, in _handle_events
    self._event_selector(event)
  File "/Users/harryday/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyomegle/pyomegle.py", line 126, in _event_selector
    self.events_handler.captcha_required()
  File "/Users/harryday/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyomegle/pyomegle.py", line 291, in captcha_required
    url = RECAPTCHA_CHALLENGE_URL % challenge
NameError: name 'RECAPTCHA_CHALLENGE_URL' is not defined
```

**Comment by eliascotto** [comment]
@harryday123 should be fixed, the variable was not referred to the instance but was supposed global. Try again.

**Comment by harrydayexe** [comment]
Sorry, didn't get a notification for this for some reason, I now have the following error, again using the default code in the README

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/harryday/.pyenv/versions/3.9.0/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/Users/harryday/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyomegle/pyomegle.py", line 31, in run
    self.instance.client_id = data['clientID']
KeyError: 'clientID'`
